services:
  rabbitmq:
    build:
      context: .
      dockerfile: ./Dockerfile.rabbitmq
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
# services:
#   rabbitmq:
#     image: rabbitmq:latest
#     container_name: rabbitmq
#     restart: always
#     ports:
#       - 5672:5672
#       - 15672:15672
#     environment:
#       RABBITMQ_DEFAULT_USER: admin
#       RABBITMQ_DEFAULT_PASS: admin
#     configs:
#       - source: rabbitmq-plugins
#         target: /etc/rabbitmq/enabled_plugins
#     volumes:
#       - rabbitmq-lib:/var/lib/rabbitmq/
#       - rabbitmq-log:/var/log/rabbitmq

# configs:
#   rabbitmq-plugins:
#     content: '[rabbitmq_management].'

# volumes:
#   rabbitmq-lib:
#     driver: local
#   rabbitmq-log:
#     driver: local
