# https://github.com/elastic/elasticsearch/blob/main/docs/reference/setup/install/docker/docker-compose.yml

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.4
    container_name: elasticsearch
    restart: on-failure
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=ChangeMeElastic123!
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./docker/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.4
    container_name: logstash
    environment:
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=ChangeMeElastic123!
    volumes:
      - ./docker/elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./docker/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.4
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "ChangeMeElastic123!"
      XPACK_ENCRYPTED_SAVED_OBJECTS_ENCRYPTIONKEY: "3f7d9a8b2c4e6f1g0h5j9k2l8m0n4p7q"
    container_name: kibana
    volumes:
      - ./docker/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  filebeat:
    build:
      context: ./docker/elk/beats/filebeat
      dockerfile: Dockerfile.filebeat
    user: root
    restart: on-failure
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=ChangeMeElastic123!
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/elk/beats/filebeat/filebeatdata:/usr/share/filebeat/data:rw
    depends_on:
      - logstash
    networks:
      - elk

  metricbeat:
    container_name: metricbeat
    build:
      context: ./docker/elk/beats/metricbeat
      dockerfile: Dockerfile.metricbeat
    user: root
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=ChangeMeElastic123!
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
    restart: on-failure
    networks:
      - elk
    depends_on:
      - elasticsearch

  heartbeat:
    container_name: heartbeat
    build:
      context: ./docker/elk/beats/heartbeat
      dockerfile: Dockerfile.heartbeat
    restart: on-failure
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=ChangeMeElastic123!
    networks:
      - elk
    depends_on:
      - elasticsearch
  apm:
    build:
      context: ./docker/elk/apm
      dockerfile: Dockerfile.apm
    ports:
      - 8200:8200
    restart: on-failure
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=ChangeMeElastic123!
      - KIBANA_HOST=http://kibana:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

  fleet-server:
    build:
      context: ./docker/elk/fleet
      dockerfile: Dockerfile.fleet
    ports:
      - 8220:8220
    restart: on-failure
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=ChangeMeElastic123!
      - KIBANA_HOST=http://kibana:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana

volumes:
  esdata:

networks:
  elk:
    driver: bridge
