# https://medium.com/norsys-octogone/a-local-environment-for-mongodb-with-docker-compose-ba52445b93ed
include:
  - docker-compose.rabbitmq.yml
  # - docker-compose.kafka.yml
  # - docker-compose.keycloak.yml
  - docker-compose.pg.yml
  # - docker-compose.elk.yml
  # - ./docker/postgres/docker-compose.pg.yml
services:
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mongodb:
    image: mongo:latest
    restart: always
    container_name: storex_mongodb_orders
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    ports:
      - '27017:27017'
    env_file:
      - .env

  # nestjs-c:
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - redis
  #     - mongodb
  #   networks:
  #     - app
  #   labels:
  #     filebeat_collector: true

volumes:
  postgres_data:
  redis:
    driver: local
  rabbitmq_data:
