services:
  sonarqube:
    # Imagem do SonarQube que será usada
    # Troque a tag de acordo com a edição/versão que você precisa:
    # - sonarqube:10.6-community (Community Edition)
    # - sonarqube:2025-lta-developer (Developer Edition LTA)
    # - sonarqube:2025-lta-enterprise (Enterprise Edition LTA)
    image: sonarqube:10.6-community

    # build:
    #   context: .
    #   dockerfile: Dockerfile.sonarqube

    container_name: sonarqube

    # Portas expostas: o SonarQube roda por padrão na 9000
    ports:
      - '9000:9000'

    # Volumes para persistência de dados e extensões
    # - sonarqube_data: índices do Elasticsearch
    # - sonarqube_extensions: plugins e drivers extras
    # - sonarqube_logs: logs da aplicação
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

    # Variáveis de ambiente para conexão ao banco
    # (Postgres é o recomendado pela própria SonarSource)
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube

    # Dependência explícita: Sonar só sobe depois do banco
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: sonarqube_db

    # Variáveis do Postgres
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube

    # Volume para persistir os dados do banco
    volumes:
      - sonarqube_postgres_data:/var/lib/postgresql/data

    # O Postgres usa a porta 5432 por padrão
    ports:
      - '5433:5432'

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_postgres_data:
# services:
#   sonarqube:
#     image: sonarqube
#     expose:
#       - 9000
#     ports:
#       - '127.0.0.1:9000:9000'
#     networks:
#       - sonarnet
#     environment:
#       - sonar.jdbc.t
#       - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
#       - sonar.jdbc.username=sonar
#       - sonar.jdbc.password=sonar
#     volumes:
#       - sonarqube_conf:/opt/sonarqube/conf
#       - sonarqube_data:/opt/sonarqube/data
#       - sonarqube_extensions:/opt/sonarqube/extensions
#       - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
# volumes:
#   sonarqube_conf:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_bundled-plugins:
