# https://medium.com/norsys-octogone/a-local-environment-for-mongodb-with-docker-compose-ba52445b93ed
services:
  tmp-keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    restart: always
    container_name: storex_keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASS}
      DB_VENDOR: h2
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASS}
    ports:
      - '8080:8080'
    env_file:
      - .env
  mongodb:
    image: mongo:latest
    restart: always
    container_name: storex_mongodb_orders
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    ports:
      - '27017:27017'
    env_file:
      - .env
