mutation CreateOrder {
  createOrder(
    input: {
      status: "PENDING"
      customerId: "123"
      paymentId: "abc"
      notes: "Entrega rápida, por favor"
      currency: "BRL"
      items: [
        {
          productId: "prod-1"
          quantity: 2
          price: { amount: 150.0, currency: "BRL" }
          seller: "Loja A"
          title: "Teclado Mecânico"
          shippingId: "ship-1"
        }
      ]
      paymentSnapshot: {
        method: "credit_card"
        status: "pending"
        amount: 300.0
      }
      shippingSnapshot: {
        status: "NOT_REQUESTED"
        carrier: "Correios"
        service: "PAC"
      }
      billingAddress: {
        street: "Rua A, 123"
        city: "São Paulo"
        state: "SP"
        zipCode: "01234-567"
      }
      customerSnapshot: { name: "João Silva", email: "js@email.com" }
    }
  ) {
    id
    status
    items {
      productId
      quantity
      price {
        amount
        currency
      }
      discount {
        couponCode
        value
        type
        currency
      }
    }
    subTotal
    total
    currency
    paymentSnapshot {
      method
      status
      amount
      installments {
        number
        value
        interestRate
        totalValue
        dueDate
      }
    }
    shippingSnapshot {
      status
      carrier
      service
    }
    billingAddress {
      street
      city
      state
      zipCode
    }
    customerSnapshot {
      name
      email
    }
    customerId
    paymentId
    notes
    discount {
      couponCode
      value
      type
      currency
    }
    active
    createdAt
    updatedAt
    deleted
    deletedAt
  }
}
