query FindOrderById {
  findOrderById(id: "6c315560-4f52-4655-bc6b-caae694e3912") {
    id
    status
    customerId

    items {
      productId
      quantity
      seller
      title
      description
      id
      price {
        amount
        currency
      }
    }
    total
  }
}
