query FindOrderById {
  findOrderById(id: "8b0cdc31-9953-457f-b89d-6311be4ad65c") {
    id
    status
    customerId

    items {
      productId
      quantity
      seller
      title
      description
      id
      price {
        amount
        currency
      }
    }
    total
  }
}
