query FindAllOrders {
  findAllOrders {
    id
    status
    items {
      productId
      quantity
      price {
        amount
        currency
      }
      discount {
        couponCode
        value
        type
        currency
      }
    }
    subTotal
    total
    currency
    paymentSnapshot {
      method
      status
      amount
      installments {
        number
        value
        interestRate
        totalValue
        dueDate
      }
    }
    shippingSnapshot {
      status
      carrier
      service
    }
    billingAddress {
      street
      city
      state
      zipCode
    }
    customerSnapshot {
      name
      email
    }
    customerId
    paymentId
    notes
    discount {
      couponCode
      value
      type
      currency
    }
    active
    createdAt
    updatedAt
    deleted
    deletedAt
  }
}
