query FindOrderById {
  findOrderById(id: "e66c8bda-9277-4902-8bb6-f0e0311e6d05") {
    id
    status
    customerId

    items {
      productId
      quantity
      seller
      title
      description
      id
      price {
        amount
        currency
      }
    }
    total
  }
}
