cluster.name: "elastic-cluster"
node.name: "es01"

network.host: 0.0.0.0
http.port: 9200

# Segurança obrigatória a partir da 9.x
xpack.security.enabled: true
xpack.security.http.ssl.enabled: false # pode deixar SSL off se for ambiente local
xpack.security.transport.ssl.enabled: false
