filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              container.labels.filebeat_collector: "true"
          config:
            - type: container
              paths:
                - /var/log/containers/*.log

output.logstash:
  hosts: ["http://logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"

logging.metrics.enabled: true
