metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "event"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  - module: elasticsearch
    metricsets:
      - node
      - node_stats
    period: 10s
    hosts: ["elasticsearch:9200"]
    username: "elastic"
    password: "ChangeMeElastic123!"

  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - socket_summary
    enabled: true
    period: 10s
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "ChangeMeElastic123!"

setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "ChangeMeElastic123!"

logging.level: info
logging.to_files: false
logging.to_stderr: true

# Performance settings
metricbeat.max_procs: 1
metricbeat.config.reload.period: 10s

# Memory settings
metricbeat.shutdown_timeout: 30s
metricbeat.max_concurrent_connections: 0

# Thread settings
metricbeat.max_procs: 1
metricbeat.config.reload.period: 10s

# Connection settings
metricbeat.max_procs: 1
metricbeat.config.reload.period: 10s

# Performance settings
metricbeat.max_procs: 1
metricbeat.config.reload.period: 10s
