metricbeat.modules:
  # Módulo Docker: Permanece o mesmo
  - module: docker
    metricsets:
      [
        "container",
        "cpu",
        "diskio",
        "event",
        "healthcheck",
        "image",
        "info",
        "memory",
        "network",
      ]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

  # Elasticsearch module (se usar module elasticsearch)
  - module: elasticsearch
    metricsets: ["node", "node_stats", "cluster_stats", "index"]
    period: 10s
    hosts: ["http://elasticsearch:9200"]
    username: "elastic"
    password: "ChangeMeElastic123!"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "ChangeMeElastic123!"

setup.kibana:
  host: "http://kibana:5601"

setup.dashboards.enabled: true
