metricbeat.modules:
  # Módulo Docker: Permanece o mesmo
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "event"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  - module: elasticsearch
    metricsets:
      - node
      - node_stats
    period: 10s
    hosts: ["elasticsearch:9200"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "senhadoelastic"

# Ele serve para configurar o Kibana com os artefatos que o Beat precisa para visualizar os dados corretamente
# Criar index patterns no Kibana (ex: filebeat-*, metricbeat-*).
# Criar dashboards pré-configurados para visualizar os dados coletados.
# O kibana_system é um usuário padrão do Elasticsearch/Kibana para que Beats façam o setup sem precisar de permissões de superusuário.
setup.kibana:
  host: "kibana:5601"
  username: "kibana_system"
  password: "KibanaSys123!"
