filebeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              docker.container.labels.filebeat_collector: "true"
          config:
            - type: container
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              processors:
                - decode_json_fields:
                    when.equals:
                      docker.container.labels.decode_log_events_to_json_object: "true"
                    fields: ["message"]
                    target: ""
                    overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]
  username: "elastic"
  password: "<password>"

setup.kibana:
  host: "http://kibana:5601" # necessário para registrar dashboards

logging.metrics.enabled: false
