# References
# https://prometheus.io/docs/prometheus/latest/installation/
# https://github.com/prometheus/prometheus/blob/main/Dockerfile

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # - prometheus_data:/prometheus
      # Compartilho o arquivo de configuração do Prometheus, que está na raiz do projeto, e vou
      # substituí-lo pelo meu arquivo de configuração la no container
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    restart: unless-stopped

  # container para monitorar recursos do sistema e containers docker
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8085:8080
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/machine-id:/etc/machine-id:ro
    privileged: true
    devices:
      - /dev/kmsg

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]

  # grafana:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana
  #   restart: unless-stopped
  #   environment:
  #     - GF_SERVER_ROOT_URL=http://my.grafana.server/
  #     - GF_PLUGINS_PREINSTALL=grafana-clock-panel
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - 'grafana_storage:/var/lib/grafana'
volumes:
  prometheus_data:
