services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - .:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - jobs-api
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - jobs-api
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '8080']
